[git_branch]
symbol = "ğŸŒ± "
truncation_length = 4
truncation_symbol = ""
#ignore_branches = ["master", "main"]

[git_commit]
commit_hash_length = 4
tag_symbol = "ğŸ”– "

[conda]
format = "[$symbol$environment](dimmed green) "

[status]
style = "bg:#000000"
symbol = "ğŸŒ§ "
success_symbol = "ğŸŒ "
not_found_symbol = "ğŸ” "
format = '[\[$symbol$signal_name$maybe_int\]]($style) '
map_symbol = true
disabled = false

[shell]
style = 'cyan bold'
